### ISSUE TITLE
Poor audio quality

### ISSUE THREAD

**Issue by dos1** [opensludge/opensludge#13]
I have noticed that, at least on GNU/Linux, the audio as played by the engine differs greatly with the same audio file as played by music player.

I suspect that SLUDGE may be doing some downsampling as a relict from old times where it was somewhat reasonable to distribute audio in 22050 Hz. Needs looking into.

**Comment by tobihan** [comment]
I didn't see this happening and the way it works is that the audio files are just handed to libalure and let that library do the rest. With which game is it happening? Could it be that it's clipping (volume too high)?

**Comment by dos1** [comment]
I tried to reproduce now, but can't. Could be my mistake when comparing compressed audio with uncompressed one, or something wrong in my system back them. I'll close it for now and will keep my eye (or actually ear) open if it ever happens in the future ;)
