### ISSUE TITLE
bass.h missing

### ISSUE THREAD

**Issue by JesperTreetop** [opensludge/opensludge#17]
I'm trying to get my macOS-building version up to date with the released version. [sound_bass.cpp](https://github.com/opensludge/opensludge/blob/master/source/Engine/sound_bass.cpp) refers to `bass.h` which is not present anywhere in the source tree.

**Comment by tobihan** [comment]
bass.h is the header of the bass sound library (from https://www.un4seen.com/).

The engine can be compiled with either of the three files sound_bass.cpp, sound_nosound.cpp or sound_openal.cpp. On linux the last one is used, on Windows and Mac OS X I think the first one was usually used.
