### ISSUE TITLE
It doesn't launch in Linux Mint Cinnamon 18 (64 bit)

### ISSUE THREAD

**Issue by ThyQueen** [opensludge/opensludge#18]
Although the program is available in the Software Manager (that's how I found it, by chance)
and you can install it from there, it doesn't launch from either the menu or the Software Manager itself.

I hope this info helps!

**Comment by dos1** [comment]
What are you actually trying to launch?

**Comment by ThyQueen** [comment]
SLUDGE. The program is available in the Software Manager, as I said above, but after installing it, it doesn't start.  I just wanted to let you know, I didn't do anything else to try to make it run though.

**Comment by dos1** [comment]
There is no such thing as "SLUDGE" app. There are things like sludge-engine, sludge-compiler, sludge-spritebankeditor etc. Also, things like sludge-engine basically do nothing unless you run it with a SLUDGE game passed as a parameter.

> but after installing it, it doesn't start

So, what do you actually expect to "start" there?

**Comment by ThyQueen** [comment]
HI Sebastian,

I was expecting to see the game engine.

I'm into gaming and making games  but I'm still learning so I hope I can
help with my information because SLUDGE looks really promising.
There are two screen shots attached so you can see what I mean. The first
one is about the description of SLUDGE as it appears in Linux Mint and the
second
is for the other related software but still it wont launch.

I only use Linux MInt and Lubuntu (SLUDGE is not available in the Software
Manager here)  on my machines so for me, stability is important to create
my projects.

I'm looking for an easy game engine to make first person adventure games
HOPA style like Mad Head Games for example.



Let me know if there is any other specific information you need.

**Comment by dos1** [comment]
Think about SLUDGE as more of a compiler. There's no single "game engine editor", like with Godot or Unity - you get a set of tools that let you create a game (make spritebanks, translations, edit floors and compile the project), and an engine that's just a runtime used to play the compiled game.

Try to launch it from the command line and you'll see what I mean. Unless there's actually some error, but in this case you should do it anyway and paste that error here ;)

**Comment by ThyQueen** [comment]
This is the terminal output:

mh@miracleshappen ~ $ SLUDGE
SLUDGE: command not found

The program is installed so I tried to locate the file but I got no result.
I uninstalled SLUDGE and then reinstalled everything again but got the same
result (just in case)

This is the result when I tried to locate the file

mh@miracleshappen ~ $ locate sludge
> /home/mh/.cache/mintinstall/screenshots/sludge-devkit_2.png
> /home/mh/.cache/mintinstall/screenshots/sludge-devkit_3.png
> /home/mh/.cache/mintinstall/screenshots/sludge-devkit_4.png
> /home/mh/.cache/mintinstall/screenshots/sludge-engine_1.png
> /home/mh/.cache/mintinstall/screenshots/sludge-engine_2.png
> /home/mh/.cache/mintinstall/screenshots/thumb_sludge-devkit_2.png
> /home/mh/.cache/mintinstall/screenshots/thumb_sludge-devkit_3.png
> /home/mh/.cache/mintinstall/screenshots/thumb_sludge-devkit_4.png
> /home/mh/.cache/mintinstall/screenshots/thumb_sludge-engine_1.png
> /home/mh/.cache/mintinstall/screenshots/thumb_sludge-engine_2.png
> /home/mh/.local/share/Trash/files/sludge egine
> /home/mh/.local/share/Trash/info/sludge egine.trashinfo
> /home/mh/Pictures/sludge_software_manager.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-floormaker.desktop
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-projectmanager.desktop
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-spritebankeditor.desktop
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-translationeditor.desktop
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-zbuffermaker.desktop
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/desktop/sludge-engine:sludge-engine.desktop
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/icons/sludge-engine.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/icons/sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/icons/sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/icons/sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/icons/sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/usr/share/app-install/icons/sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-28_09-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-engine_sludge-engine.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-floormaker.desktop
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-projectmanager.desktop
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-spritebankeditor.desktop
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-translationeditor.desktop
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-zbuffermaker.desktop
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/desktop/sludge-engine:sludge-engine.desktop
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/icons/sludge-engine.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/icons/sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/icons/sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/icons/sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/icons/sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/usr/share/app-install/icons/sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-29_09-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-engine_sludge-engine.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-floormaker.desktop
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-projectmanager.desktop
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-spritebankeditor.desktop
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-translationeditor.desktop
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-zbuffermaker.desktop
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/desktop/sludge-engine:sludge-engine.desktop
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/icons/sludge-engine.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/icons/sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/icons/sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/icons/sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/icons/sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/usr/share/app-install/icons/sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-30_11-00-01/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-engine_sludge-engine.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-floormaker.desktop
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-projectmanager.desktop
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-spritebankeditor.desktop
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-translationeditor.desktop
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/desktop/sludge-devkit:sludge-zbuffermaker.desktop
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/desktop/sludge-engine:sludge-engine.desktop
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/icons/sludge-engine.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/icons/sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/icons/sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/icons/sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/icons/sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/usr/share/app-install/icons/sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/cache/apt/archives/sludge-engine_2.2.1-1build2_amd64.deb
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-floormaker.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-projectmanager.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-spritebankeditor.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-translationeditor.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-zbuffermaker.png
>
> /timeshift/snapshots/2019-03-31_14-00-02/localhost/var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-engine_sludge-engine.png
> /usr/bin/sludge-compiler
> /usr/share/app-install/desktop/sludge-devkit:sludge-floormaker.desktop
> /usr/share/app-install/desktop/sludge-devkit:sludge-projectmanager.desktop
>
> /usr/share/app-install/desktop/sludge-devkit:sludge-spritebankeditor.desktop
>
> /usr/share/app-install/desktop/sludge-devkit:sludge-translationeditor.desktop
> /usr/share/app-install/desktop/sludge-devkit:sludge-zbuffermaker.desktop
> /usr/share/app-install/desktop/sludge-engine:sludge-engine.desktop
> /usr/share/app-install/icons/sludge-engine.png
> /usr/share/app-install/icons/sludge-floormaker.png
> /usr/share/app-install/icons/sludge-projectmanager.png
> /usr/share/app-install/icons/sludge-spritebankeditor.png
> /usr/share/app-install/icons/sludge-translationeditor.png
> /usr/share/app-install/icons/sludge-zbuffermaker.png
> /usr/share/doc/sludge-compiler
> /usr/share/doc/sludge-compiler/changelog.Debian.gz
> /usr/share/doc/sludge-compiler/copyright
> /usr/share/man/man1/sludge-compiler.1.gz
> /var/cache/apt/archives/sludge-compiler_2.2.1-1build2_amd64.deb
> /var/cache/apt/archives/sludge-devkit_2.2.1-1build2_amd64.deb
> /var/cache/apt/archives/sludge-engine_2.2.1-1build2_amd64.deb
>
> /var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-floormaker.png
>
> /var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-projectmanager.png
>
> /var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-spritebankeditor.png
>
> /var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-translationeditor.png
>
> /var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-devkit_sludge-zbuffermaker.png
>
> /var/lib/app-info/icons/ubuntu-xenial-universe/64x64/sludge-engine_sludge-engine.png
> /var/lib/dpkg/info/sludge-compiler.list
> /var/lib/dpkg/info/sludge-compiler.md5sums
> /var/lib/dpkg/info/sludge-devkit.list
> /var/lib/dpkg/info/sludge-devkit.postrm
>
>>
>>
 This is all!

**Comment by dos1** [comment]
`ls /usr/bin/sludge*` ?

**Comment by ThyQueen** [comment]
This is the output:

mh@miracleshappen ~ $ ls /usr/bin/sludge* ?
ls: cannot access '?': No such file or directory
/usr/bin/sludge-compiler        /usr/bin/sludge-spritebankeditor
/usr/bin/sludge-floormaker      /usr/bin/sludge-translationeditor
/usr/bin/sludge-projectmanager  /usr/bin/sludge-zbuffermaker
mh@miracleshappen ~ $

However, in the programming section of the menu I can see and access a
bunch of stuff.
Here's a screenshot (see attachment).

I have no idea about your target users,  in the past I was learning with
the Blender Game Engine which has logic bricks that help you
a lot with making a game fairly quickly. However, Blender 2.8 (the next
one) won't have the game engine any more because they decided to
fork it out as UPBGE and Armory. I really want to make games without having
to go into coding so much so I would love to have something
which follows something similar to the logic bricks in Blender (still need
some python coding but it doesn't seem extremely difficult).
At the moment I'm just using a non open source game engine called RPG Maker
VX Ace which is a lot of fun and you can make games with no coding at all
but you can add your code if you want to (Ruby based).

Let me know if I can help you with something else.

**Comment by dos1** [comment]
Looks like everything is alright.

From your description I'd say that SLUDGE is simply not what you're looking for. It's pretty much a programming language, more comparable to C or Python than to Blender Game Engine or RPG Maker.

For your needs, I'd recommend you to take a look at GDevelop instead, which actually aims at allowing you to make a game from blocks without coding; or if you need something more advanced, recent versions of Godot Engine got visual scripting support as well.

**Comment by ThyQueen** [comment]
Ok! Thank you for your help.
