### ISSUE TITLE
Support of displaying non-english text 

### ISSUE THREAD

**Issue by aprekates** [opensludge/opensludge#4]
I added with the translation editor  some greek text but when i compile and run
squares are displayed in the game instead of text.
Isnt  utf8 text suporrted ?

**Comment by tobihan** [comment]
UTF-8 is supported, but you have to use a font containing the characters you are using. I think there is no greek font yet, so you have to create one. You can take the Verb Coin Example as an example, it also uses a second font with more characters when the language is set to German. You can find it here: https://opensludge.github.io/resources.html#sourcecode

**Comment by aprekates** [comment]
Thanks for the response.

I downloaded and compiled Verbcoin from within Sludge's project manager and i got an error:
ERROR: invalid string found. (It is not UTF-8 encoded)(in init.slu)

**Comment by tobihan** [comment]
You are right, that download was never updated to UTF-8. There is an updated version of the Verb Coin example included in with the SLUDGE source code under doc/ExampleProjects/VerbCoin.

**Comment by aprekates** [comment]
Ok. i compiled it and it runs ok . i'll try to find a way to display greek as  u said.

**Comment by tobihan** [comment]
Note that you can just write "a b c ..." on a transparent background
with a program like GIMP or Photoshop, maybe apply a contour effect and
import it with the Fontify function in the Sprite Bank Editor (see [1])
to get a font in the SLUDGE sprite bank format.

[1]
https://opensludge.github.io/opensludge/doc/SLUDGEDevKitHelp/About_the_SLUDGE_Sprite_Bank_Editor.html
